### ISSUE TITLE
Problem on Centos 7 vps

### ISSUE THREAD

**Issue by Xenaxx** [BGInfinityX/Dark-Matter-Layer-7-DDoS#2]
[root@localhost ~]$ python DarkMatter.py
Welcome To DarkMatter DDoS
IP/Domain: https://o-tacos.com/
Traceback (most recent call last):
  File "DarkMatter.py", line 7, in <module>
    ip = input("IP/Domain: ")
  File "<string>", line 1
    https://o-tacos.com/
         ^
SyntaxError: invalid syntax
[root@localhost ~]$

How i solver this ?
Thanks for ur work and your help !

**Comment by BGInfinityX** [comment]
Use o-tacos.com instead of https://o-tacos.com/, i will add support for http:// and https:// (SSL) in the next version :)
