### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 136yeahh** [BGInfinityX/Dark-Matter-Layer-7-DDoS#5]
--$ python DarkMatter.py
Welcome to DarkMatter DDoS
IP/Domain: 194.163.147.84
Traceback (most recent call last):
File "DarkMatter.py", line 7, in <module>
ip = input("IP/Domain: ")
File "<String>", line 1
194.163.147.84
                 ^
SyntaxError: invalid syntax

**Comment by BGInfinityX** [comment]
Use: python3 DarkMatter.py
